BioBalanceShop/Areas/Admin/Controllers/UserController.cs
using BioBalanceShop.Core.Contracts;
using BioBalanceShop.Core.Models.Admin.User;
using BioBalanceShop.Infrastructure.Data.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using static BioBalanceShop.Core.Constants.RoleConstants;
using static BioBalanceShop.Infrastructure.Constants.CustomClaims;

namespace BioBalanceShop.Areas.Admin.Controllers
{
    public class UserController : AdminBaseController
    {
        private readonly IUserService _userService;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly ILogger<UserController> _logger;

        public UserController(
            IUserService userService,
            UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager,
            ILogger<UserController> logger)
        {
            _userService = userService;
            _userManager = userManager;
            _signInManager = signInManager;
            _logger = logger;
        }

        [HttpGet]
        public async Task<IActionResult> All([FromQuery] AdminUserAllGetModel model)
        {
            try
            {
                var users = await _userService.AllAsync(
                model.Role,
                model.SearchTerm,
                model.Sorting,
                model.CurrentPage,
                model.UsersPerPage);

                model.TotalUsersCount = users.TotalUsersCount;
                model.Users = users.Users;
                model.Roles = await _userService.GetAllRoles();

                return View(model);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Admin/UserController/All/Get");
                return new StatusCodeResult(StatusCodes.Status500InternalServerError);
            }
        }

        [HttpPost]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (await _userManager.FindByIdAsync(id) == null)
            {
                return BadRequest();
            }

            try
            {
                var currentUser = await _userManager.GetUserAsync(User);

                if (currentUser.Id == id)
                {
                    await _userService.DeleteUserByIdAsync(id);
                    await _signInManager.SignOutAsync();
                    return RedirectToAction("Login", "Account", new { area = "Identity" });
                }

                await _userService.DeleteUserByIdAsync(id);
                return RedirectToAction(nameof(All));
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Admin/UserController/DeleteConfirmed/Post");
                return new StatusCodeResult(StatusCodes.Status500InternalServerError);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            AdminUserEditFormModel? model = await _userService.GetUserByIdAsync(id);

            if (model == null)
            {
                return BadRequest();
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(AdminUserEditFormModel model)
        {
            var modelUser = await _userManager.FindByIdAsync(model.Id);

            if (modelUser == null)
            {
                return BadRequest();
            }

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                var currentUser = await _userManager.GetUserAsync(User);

                var modelUserName = $"{modelUser.FirstName} {modelUser.LastName}";
                var modelUserClaims = await _userManager.GetClaimsAsync(modelUser);
                var modelUserFullNameClaim = modelUserClaims.FirstOrDefault(c => c.Value == modelUserName);
                var newFullNameClaim = new Claim(UserFullNameClaim, $"{model.FirstName} {model.LastName}");

                await _userService.EditUserAsync(model);

                await _userManager.ReplaceClaimAsync(modelUser, modelUserFullNameClaim, newFullNameClaim);

                if (currentUser != null && await _userManager.IsInRoleAsync(currentUser, AdminRole) == false)
                {
                    await _signInManager.SignOutAsync();
                    return RedirectToAction("Login", "Account", new { area = "Identity" });
                }

                if (currentUser.Id == model.Id)
                {
                    await _signInManager.RefreshSignInAsync(currentUser);
                }

                return RedirectToAction(nameof(All));
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Admin/UserController/Edit/Post");
                return new StatusCodeResult(StatusCodes.Status500InternalServerError);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            try
            {
                AdminUserCreateFormModel model = new AdminUserCreateFormModel();
                model.Roles = await _userService.GetAllRoles();

                return View(model);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Admin/UserController/Create/Get");
                return new StatusCodeResult(StatusCodes.Status500InternalServerError);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Create(AdminUserCreateFormModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    model.Roles = await _userService.GetAllRoles();
                    return View(model);
                }

                await _userService.CreateUserAsync(model);

                return RedirectToAction(nameof(All));
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Admin/UserController/Create/Post");
                return new StatusCodeResult(StatusCodes.Status500InternalServerError);
            }
        }
    }
}

BioBalanceShop/Controllers/OrderController.cs
using BioBalanceShop.Core.Contracts;
using BioBalanceShop.Core.Models.Order;
using BioBalanceShop.Infrastructure.Data.Enumerations;
using BioBalanceShop.Infrastructure.Data.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace BioBalanceShop.Controllers
{
    public class OrderController : BaseController
    {
        private readonly IOrderService _orderService;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ILogger _logger;

        public OrderController(
            IOrderService orderService,
            UserManager<ApplicationUser> userManager,
            ILogger<OrderController> logger)
        {
            _orderService = orderService;
            _userManager = userManager;
            _logger = logger;
        }

        [HttpGet]
        public async Task<IActionResult> MyOrders([FromQuery] OrderAllGetModel model)
        {
            try
            {
                var orders = await _orderService.AllAsync(
                model.OrderStatus,
                model.SearchTerm,
                model.Sorting,
                model.CurrentPage,
                model.OrdersPerPage,
                User.Id());

                model.TotalOrdersCount = orders.TotalOrdersCount;
                model.Orders = orders.Orders;
                model.OrderStatuses = Enum.GetValues(typeof(OrderStatus)).Cast<OrderStatus>().ToList();

                return View(model);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "OrderConroller/MyOrders/Get");
                return new StatusCodeResult(StatusCodes.Status500InternalServerError);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            if (!await _orderService.ExistsAsync(id))
            {
                return BadRequest();
            }

            if (await _orderService.GetUserIdByOrderIdAsync(id) != User.Id())
            {
                return Unauthorized();
            }

            var model = await _orderService.GetOrderByIdAsync(id, User.Id());
            
            if (model == null)
            {
                return BadRequest();
            }

            return View(model);
        }
    }
}

BioBalanceShop/Controllers/ProductController.cs
using BioBalanceShop.Core.Contracts;
using BioBalanceShop.Core.Extensions;
using BioBalanceShop.Core.Models.Product;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BioBalanceShop.Controllers
{
    public class ProductController : BaseController
    {
        private readonly IProductService _productService;
        private readonly IShopService _shopService;
        private readonly ILogger _logger;

        public ProductController(
            IProductService productService,
            IShopService shopService,
            ILogger<ProductController> logger)
        {
            _productService = productService;
            _shopService = shopService;
            _logger = logger;
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> All([FromQuery] ProductAllServiceModel model)
        {
            try
            {
                var products = await _productService.AllAsync(
                model.Category,
                model.SearchTerm,
                model.Sorting,
                model.CurrentPage,
                model.ProductsPerPage);

                model.TotalProductsCount = products.TotalProductsCount;
                model.Products = products.Products;
                model.Categories = await _productService.AllCategoryNamesAsync();

                return View(model);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "ProductConroller/All/Get");
                return new StatusCodeResult(StatusCodes.Status500InternalServerError);
            }
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> Details(int id, string productInfo)
        {
            var model = await _productService.GetProductByIdAsync(id);

            if (model == null) {
                return BadRequest();
            }

            if (productInfo != model.GetProductInfo())
            {
                return BadRequest();
            }

            string? addedToCartMessage = TempData["AddedToCartMessage"] as string;

            ViewBag.SiteMessage = addedToCartMessage ?? "";

            return View(model);
        }
    }
}

BioBalanceShop/Areas/Admin/Views/Shared/_AdminLoginPartial.cshtml
@using BioBalanceShop.Infrastructure.Data.Models
@using Microsoft.AspNetCore.Identity
@using System.Security.Claims
@using BioBalanceShop.Infrastructure.Constants

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@{
    string userName = string.Empty;

    if (SignInManager.IsSignedIn(User))
    {
        userName = User.FindFirstValue(BioBalanceShop.Infrastructure.Constants.CustomClaims.UserFullNameClaim) ?? string.Empty;
    }
}

<ul class="navbar-nav">
    @if (SignInManager.IsSignedIn(User))
    {
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Hello @userName!</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index" title="To Shop">To Shop</a>
        </li>
        <li class="nav-item">
            <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Dashboard", "Home", new { area = "Admin" })">
                <button type="submit" class="nav-link btn btn-link text-dark">Logout</button>
            </form>
        </li>
    }
    else
    {
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Login">Login</a>
        </li>
    }
</ul>

BioBalanceShop/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bio Balance - Admin area</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/mainMenu.css" asp-append-version="true" />
    @await RenderSectionAsync("Styles", required: false)
</head>
<body> 
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img id="site-logo" src="~/images/BioBalanceShop_logo.png" alt="Bio Blanace logo" width="350" height="71" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @await Component.InvokeAsync(nameof(AdminMenuComponent))
                    <partial name="_AdminLoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Today.Year - Bio Balance
            <span class="text-danger">Admin Area</span>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BioBalanceShop/Areas/Admin/Views/Shared/_OrderPartial.cshtml
@model AdminOrderAllServiceModel

<tr>
    <td>
        <label>@Model.OrderNumber</label>
    </td>
    <td>
        <label>@Model.OrderDate.ToShortDateString()</label>
    </td>
    <td>
        <label>@Model.OrderItemsCount items</label>
    </td>
    <td>
        <label>
            @if (Model.Currency.CurrencyIsSymbolPrefix)
            {
                @Model.Currency.CurrencySymbol
            }
            @String.Format("{0:f2}", Model.TotalAmount)
            @if (!Model.Currency.CurrencyIsSymbolPrefix)
            {
                @Model.Currency.CurrencySymbol
            }
        </label>
    </td>
    <td>
        <label>@Model.Status</label>
    </td>
    <td>
        <a asp-area="Admin" asp-controller="Order" asp-action="EditStatus" asp-route-id="@Model.Id" class="btn btn-warning mb-2 w-100 p-3 fw-bold">Edit Status</a>
    </td>
</tr>

BioBalanceShop/Areas/Admin/Views/Shared/_ProductModalPartial.cshtml
<div class="modal fade" id="modalConfirmDelete" tabindex="-1" role="dialog" aria-labelledby="ConfirmDelete" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="ConfirmDelete">Delete</h5>
            </div>
            <div class="modal-body">
                Are you sure you want to delete product <span id="productName"></span>?
            </div>
            <div class="modal-footer">
                <form asp-area="Admin" asp-controller="Product" asp-action="DeleteConfirmed" method="post">
                    <input id="deleteProduct" type="hidden" name="id" />
                    <button type="submit" class="btn btn-danger">Confirm Delete</button>
                </form>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>

BioBalanceShop/Areas/Admin/Views/Shared/_ProductPartial.cshtml
@model AdminProductServiceModel
@inject IProductService adminProductService

<tr>
    <td>
        <label><img class="card-img-top" src="@Model.ImageUrl" alt="Product Image" width="100" height="100"></label>
    </td>
    <td>
        <label>@Model.ProductCode</label>
    </td>
    <td>
        <label>@Model.Title</label>
    </td>
    <td>
        <label>@Model.Quantity</label>
    </td>
    <td>
        <label>
            @if (Model.Currency.CurrencyIsSymbolPrefix)
            {
                @Model.Currency.CurrencySymbol
            }
            @String.Format("{0:f2}", Model.Price)
            @if (!Model.Currency.CurrencyIsSymbolPrefix)
            {
                @Model.Currency.CurrencySymbol
            }
        </label>
    </td>
    <td>
        <a asp-area="Admin" asp-controller="Product" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-warning mb-2 w-100 p-3 fw-bold">Edit</a>
    </td>
    <td>
        <button class="btn btn-danger mb-2 w-100 p-3 fw-bold openModalBtn" data-product="@Model.Title" data-id="@Model.Id">Delete</button>
    </td>
</tr>

BioBalanceShop/Areas/Admin/Views/Shared/_SiteMessagePartial.cshtml
@if (!string.IsNullOrEmpty(ViewBag.SiteMessage))
{
    <div id="siteMsgContainer">
        <div id="siteMsg">@ViewBag.SiteMessage<span id="siteMsgClose">X</span></div>
    </div>
}

BioBalanceShop/Areas/Admin/Views/Shared/_UserModalPartial.cshtml
<div class="modal fade" id="modalConfirmDelete" tabindex="-1" role="dialog" aria-labelledby="ConfirmDelete" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="ConfirmDelete">Delete</h5>
            </div>
            <div class="modal-body">
                Are you sure you want to delete user <span id="userName"></span>?
            </div>
            <div class="modal-footer">
                <form asp-area="Admin" asp-controller="User" asp-action="DeleteConfirmed" method="post">
                    <input id="deleteUser" type="hidden" name="id" />
                    <button type="submit" class="btn btn-danger">Confirm Delete</button>
                </form>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>

BioBalanceShop/Areas/Admin/Views/Shared/_UserPartial.cshtml
@model AdminUserServiceModel

<tr>
    <td>
        <label>@Model.UserName</label>
    </td>
    <td>
        <label>@Model.Email</label>
    </td>
    <td>
        <label>@Model.FirstName</label>
    </td>
    <td>
        <label>@Model.LastName</label>
    </td>
    <td>
        <label>@Model.PhoneNumber</label>
    </td>
    <td>
        @if (Model.IsAdmin)
        {
            <label>✔</label>
        }
        else
        {
            <label class="text-center">❌</label>
        }
    </td>
    <td>
        <a asp-area="Admin" asp-controller="User" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-warning mb-2 w-100 p-3 fw-bold">Edit</a>
    </td>
    <td>
        <button class="btn btn-danger mb-2 w-100 p-3 fw-bold openModalBtn" data-user="@Model.UserName" data-id="@Model.Id">Delete</button>
    </td>
</tr>